---
title: "CQI_coffee"
subtitle: ""
author: "Jean Dos Santos"
date: "August 2020"
output:
  word_document:
    highlight: tango
    toc: yes
    toc_depth: 2
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    highlight: tango
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE, fig.align = "center")
```

# Import Packages

```{r}
if(!require(pacman, quietly = TRUE)){ install.packages("pacman", quiet = TRUE, verbose = FALSE) }
pacman::p_load(caret, tidyverse, magrittr, tidyselect, assertive, stringi, janitor, gdata, tools, renv, install = TRUE, update = FALSE)
```

```{r}
print_plots <- TRUE
save_plots <- TRUE
save_plots_dir <- "results/charts/"
custom_messages <- TRUE
```



***

# Import Data

```{r}
raw_arabica <- read_csv("data/arabica_ratings_raw.csv")
raw_robusta <- read_csv("data/robusta_ratings_raw.csv")
```


# Data Cleaning

```{r}
print_dimensions(raw_arabica, message = FALSE)
print_dimensions(raw_robusta, message = FALSE)
```

```{r}
print_colnames(raw_arabica)
print_colnames(raw_robusta)
```


```{r}
arabica <- rm_starts_with(raw_arabica) %>% janitor::remove_empty(which = "cols") 
robusta <- rm_starts_with(raw_robusta) %>% janitor::remove_empty(which = "cols") 

cols_in_ara <- setdiff(colnames(arabica), colnames(robusta))
cols_in_rob <- setdiff(colnames(robusta), colnames(arabica))
cols_in_both <- intersect(colnames(arabica), colnames(robusta))

print_intro("Columns in arabica only:\n", cols_in_ara, sep = " |")
print_intro("Columns in robusta only:\n", cols_in_rob, sep = " |")
print_intro("Columns in both tables:\n", cols_in_both, sep = " |")
```
```{r}
arabica <- clean_colnames(arabica) %>% janitor::remove_empty(which = "cols")
robusta <- clean_colnames(robusta) %>% janitor::remove_empty(which = "cols")
arabica$NOTES <- NULL

cols_in_ara <- setdiff(colnames(arabica), colnames(robusta))
cols_in_rob <- setdiff(colnames(robusta), colnames(arabica))
cols_in_both <- intersect(colnames(arabica), colnames(robusta))

print_intro("Columns in arabica only:\n", cols_in_ara, sep = " |")
print_intro("Columns in robusta only:\n", cols_in_rob, sep = " |")
print_intro("Columns in both tables:\n", cols_in_both, sep = " |")

robusta <-  gdata::rename.vars(robusta, 
                               from = c("FRAGRANCE_AROMA", "SALT_ACID", "BITTER_SWEET", "MOUTHFEEL", "UNIFORM_CUP"), 
                               to = c("AROMA", "ACIDITY", "SWEETNESS", "BODY", "UNIFORMITY"), info = TRUE)

merged_df <- merge(arabica, robusta, all=TRUE)
print_dimensions(merged_df)

if(print_plots){ custom_visdat(merged_df, title = "Coffee CQI dataset after merging arabica and robusta datasets", save_plot = save_plots, save_dir = save_plots_dir) }

# merged_df[merged_df$SPECIES == "Robusta", cols_in_ara]
# merged_df[merged_df$SPECIES == "Arabica", cols_in_rob]
```


```{r}
merged_dtypes <- sapply(merged_df, class)

print_intro("Numeric features:\n", names(merged_dtypes)[merged_dtypes == "numeric"])
print_intro("Non-numeric features:\n", names(merged_dtypes)[merged_dtypes != "numeric"])

# merged_df[, merged_dtypes == "numeric"]
# merged_df[, merged_dtypes == "character"]

```



***

## Process Countries of Origin

```{r}
print_intro("Countries of origin:\n", merged_df$COUNTRY_OF_ORIGIN %>% unique() %>% sort(), sep = " |")

print_intro(intro = "Entries with missing Country of origin:\n")
merged_df[is.na(merged_df$COUNTRY_OF_ORIGIN), c('OWNER', "PRODUCER", "CERTIFICATION_BODY", "CERTIFICATION_ADDRESS")]

# Assign entry with missing Country to Colombia

merged_df[is.na(merged_df$COUNTRY_OF_ORIGIN), "COUNTRY_OF_ORIGIN"] <- "Colombia"
```
```{r}
tot_mod <- 0

for (i in 1:nrow(merged_df)){
  
  country <- merged_df$COUNTRY_OF_ORIGIN[i]
  # print(country)
  
  country_clean <- country %>% 
    str_replace("Cote d\\?Ivoire", "Ivory Coast") %>% 
    str_replace(", United Republic Of", "") %>% 
    str_replace("United States", "USA")
  
  if (country_clean != country) { 
    
    merged_df$COUNTRY_OF_ORIGIN[i] <- country_clean
    cat("row", i, "Changed from:", country, "to:", country_clean, "\n")
    tot_mod <- tot_mod + 1
    
  }
}

print_intro("\nNumber of entries modified: ", tot_mod, eol = "\n", message = FALSE)

table(merged_df$COUNTRY_OF_ORIGIN) %>% sort(decreasing = TRUE) %>% data.frame()
```
***

## Process Region

```{r}
print_intro(intro = "First entries of `REGION`:\n", merged_df$REGION %>% head(20), sep = " |", message = FALSE)
print_intro(intro = "Last entries of `REGION`:\n", merged_df$REGION %>% tail(20), sep = " |", message = FALSE)

merged_df$REGION <- clean_text(merged_df$REGION)

print_intro(intro = "First entries of cleaned `REGION`:\n", merged_df$REGION %>% head(20), sep = " |", message = FALSE)
print_intro(intro = "Last entries of cleaned `REGION`:\n", merged_df$REGION %>% tail(20), sep = " |", message = FALSE)

# merged_df$REGION %>% table() %>% sort(decreasing = TRUE) %>% head(25)
```

## Process Harvest Year

```{r}
print_intro(intro = "Unique entries for `HARVEST_YEAR` before extraction:\n", merged_df$HARVEST_YEAR %>% unique() %>% sort(), sep = " |", message = FALSE)

merged_df$HARVEST_YEAR <- extract_year(merged_df$HARVEST_YEAR)

print_intro(intro = "Unique entries for `HARVEST_YEAR` after extraction:\n", merged_df$HARVEST_YEAR %>% unique() %>% sort(), sep = " |", message = FALSE)

merged_df$HARVEST_YEAR %>% summary()
print_total_NA(merged_df$HARVEST_YEAR)

if(print_plots){ merged_df$HARVEST_YEAR %>% hist(., main = "Distribution of Harvest Year", xlab = "Harvest Year", ) }
```
Most records are graded during the same year of the harvest year

Use Grading year to impute missing harvest year

```{r}
merged_df$GRADING_YEAR <- merged_df$GRADING_DATE %>% extract_year() 

print_intro("Average difference between grading year and harvest year: ", mean(merged_df$GRADING_YEAR[!is.na(merged_df$HARVEST_YEAR)] - merged_df$HARVEST_YEAR[!is.na(merged_df$HARVEST_YEAR)]) %>% round(4))

# impute missing harvest year with grading year
merged_df$HARVEST_YEAR[is.na(merged_df$HARVEST_YEAR)] <- merged_df$GRADING_YEAR[is.na(merged_df$HARVEST_YEAR)]

merged_df$HARVEST_YEAR %>% summary()
print_total_NA(merged_df$HARVEST_YEAR)
```

## Process Altitude

```{r}
print_intro(intro = "Unique entries for `ALTITUDE` before cleaning:\n", merged_df$ALTITUDE %>% unique() %>% sort(), sep = " |", message = FALSE)
print_total_NA(merged_df$ALTITUDE)
```

```{r}
clean_altitude <- function(text, text_case = "upper", 
                       rm_accents = TRUE, accents_to = "Latin-ASCII", 
                       rm_redundant = TRUE, redundant_regex = "test|TEST|n\\/a|N\\/A|unkown|none|average", 
                       rm_punct = TRUE, punct_regex = "\\||\\.|\\;|\\:|\\(|\\)|\\~|\\,|\\+",
                       sub_w_space = TRUE, sub_w_space_regex = ",|/|-",
                       replace_NA = TRUE, NA_regex = "",
                       rm_numbers = TRUE, sub_double_space = TRUE){
  
  clean_text <- text %>% 
    stringr::str_to_lower() %>% 
    { if(rm_accents) stringi::stri_trans_general(., accents_to) else .} %>% 
    { if(rm_redundant) stringr::str_remove_all(., redundant_regex) else .} %>% 
    { if(rm_punct) stringr::str_remove_all(., punct_regex) else .} %>% 
    { if(sub_w_space) stringr::str_replace_all(., sub_w_space_regex, " ") else .} %>% 
    { if(rm_numbers) stringr::str_remove_all(., "[0-9]") else .} %>% 
    { if(sub_double_space) stringr::str_replace_all(., " {2,}", " ") else .} %>% 
    { if(replace_NA) stringr::str_replace_na(., replacement = NA_regex) else .} %>% 
    stringr::str_remove_all(., " $|^ ") %>% 
    stringi::stri_trans_general(., id = text_case)
  
  return(clean_text)
  
}

altitude_text <- merged_df$ALTITUDE %>% 
    stringr::str_to_lower() %>% 
    { if(rm_accents) stringi::stri_trans_general(., accents_to) else .} %>% 
    { if(rm_redundant) stringr::str_remove_all(., redundant_regex) else .} %>% 
    { if(rm_punct) stringr::str_remove_all(., punct_regex) else .} %>%
    { if(sub_w_space) stringr::str_replace_all(., sub_w_space_regex, " ") else .} %>% 
    { if(rm_numbers) stringr::str_remove_all(., "[0-9]") else .} %>% 
    { if(sub_double_space) stringr::str_replace_all(., " {2,}", " ") else .} %>% 
    { if(replace_NA) stringr::str_replace_na(., replacement = NA_regex) else .} %>% 
    stringr::str_remove_all(., " $|^ ") %>% 
    stringi::stri_trans_general(., id = text_case)

altitude_text[altitude_text == ""] <- NA

altitude_numeric <- merged_df$ALTITUDE %>% 
    { if(rm_punct) stringr::str_remove_all(., punct_regex) else .} %>%
    stringr::str_replace_all(., pattern = "[:punct:]", replacement = " ") %>%   
    stringr::str_remove_all(., pattern = "[:alpha:]") %>% 
    { if(sub_double_space) stringr::str_replace_all(., " {2,}", " ") else .} %>% 
    { if(replace_NA) stringr::str_replace_na(., replacement = NA_regex) else .} %>% 
    stringr::str_remove_all(., " $|^ ") %>% 
    stringr::str_extract_all(., "[0-9]+", simplify = TRUE) %>% 
    apply(., 2, as.numeric) %>% 
    data.frame() %>% 
    apply(., MARGIN = 1, mean, na.rm=TRUE)

altitude_numeric %>% summary()
altitude_numeric %>% hist(main = "Histogram of Altitude Values: Before Transformation of Outliers", xlab = "Values")
altitude_numeric <- outlier_to_NA(altitude_numeric, min_threshold = 0, max_threshold = 20000)
altitude_numeric %>% hist(main = "Histogram of Altitude Values: After Transformation of Outliers", xlab = "Values")
```

```{r}
feet_regex <- "FT|FEET|PIES|PSN|^F$"
meter_regex <- "^M|METRE|METER|MASL|MT[S]*|MS[N]*M|公尺"
regex_vec <- c("m" = meter_regex, "ft" = feet_regex)

assigned_unit <- regex_assign(altitude_text, regex_vec = regex_vec, exclude_na = TRUE, verbose = TRUE)

data.frame(altitude_numeric, assigned_unit) %>% 
  filter(!is.na(assigned_unit)) %>% 
  ggplot(aes(x = altitude_numeric, fill = assigned_unit)) +
    geom_histogram(bins=20, col = "white", alpha = 0.75) +
    labs(x = "Altitude", y = "Count", fill = "Assigned Unit") +
    scale_fill_brewer(type = "qual", palette = "Set1", na.value = "grey") +
    theme_minimal()

data.frame(altitude_numeric, assigned_unit) %>% 
  ggplot(aes(x = altitude_numeric, fill = assigned_unit)) +
    geom_histogram(bins=20, col = "white", alpha = 0.75) +
    labs(x = "Altitude", y = "Count", fill = "Assigned Unit") +
    scale_fill_brewer(type = "qual", palette = "Set1", na.value = "grey") +
    theme_minimal()

    
```


```{r}
# Assign units to altitude values based on numeric value
threshold <- 3000
altitude_unit <- assigned_unit

altitude_unit[(altitude_numeric > threshold) & (is.na(altitude_unit)) & (!is.na(altitude_numeric))] <- "ft"
altitude_unit[(altitude_numeric <= threshold) & (is.na(altitude_unit)) & (!is.na(altitude_numeric))] <- "m"

data.frame(altitude_numeric, altitude_unit) %>% 
  ggplot(aes(x = altitude_numeric, fill = altitude_unit)) +
    geom_histogram(bins=20, col = "white", alpha = 0.75) +
    labs(x = "Altitude", y = "Count", fill = "Assigned Unit") +
    scale_fill_brewer(type = "qual", palette = "Set1", na.value = "grey") +
    theme_minimal()

convert_ft_to_m <- function(x, dec = 2){ return( round(x*0.3048000, 2) ) }

merged_df$ALTITUDE_M <- NA
merged_df$ALTITUDE_M[(altitude_unit == "m") & (!is.na(altitude_unit))] <- altitude_numeric[(altitude_unit == "m") & (!is.na(altitude_unit))]

merged_df$ALTITUDE_M[(altitude_unit == "ft") & (!is.na(altitude_unit))] <- convert_ft_to_m(altitude_numeric[(altitude_unit == "ft") & (!is.na(altitude_unit))])
```


```{r}
merged_df$ALTITUDE_M %>% summary()
merged_df$ALTITUDE_M <- outlier_to_NA(merged_df$ALTITUDE_M, max_threshold = 8000)

merged_df %>% 
  ggplot(aes(x = ALTITUDE_M)) +
    geom_histogram(bins=20, col = "white", alpha = 0.75) +
    labs(x = "Altitude (m)", y = "Count", 
         title = "Distribution of Altitude Values (in meters)",
         subtitle = "Values were transformed and measurements in feet were converted to metric system") +
    theme_minimal()

merged_df %>% 
  dplyr::select(ALTITUDE, ALTITUDE_M) %>% 
  dplyr::filter(!is.na(ALTITUDE), !is.na(ALTITUDE_M)) %>% 
  dplyr::distinct() %>% 
  head(50)
```

## Remove non-relevant features

```{r}
merged_df %>% colnames()

# Impute missing OWNER with PRODUCER
merged_df$OWNER[is.na(merged_df$OWNER)] <- merged_df$PRODUCER[is.na(merged_df$OWNER)]

non_rel_features <- c("LOT_NUMBER", "FARM_NAME", "ALTITUED", "MILL", "ICO_NUMBER", "COMPANY", "NUMBER_OF_BAGS", "BAG_WEIGHT", "PRODUCER", "IN-COUNTRY_PARTNER", "GRADING_DATE", "OWNER_1", "STATUS", "EXPIRATION", "CERTIFICATION_BODY", "CERTIFICATION_ADDRESS", "CERTIFICATION_CONTACT", "GRADING_YEAR")

# remove non-relevant features
merged_df <- merged_df %>% dplyr::select(-non_rel_features)

custom_visdat(merged_df, text_angle = 45)
```



































































